name: publish

on:
  push:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Install build tool
      run: npm install -g pnpm
    - name: Install Dependencies
      run: cd ko-KR ; pnpm i
    - name: Generate pages
      run: cd ko-KR ; pnpm run build
    - name: Deploy to GitHub Pages
      uses: comfuture/actions/ghpages@master
      env:
        BUILD_DIR: ko-KR/.vitepress/dist/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
